(define (domain warehouse-domain)
  (:requirements :typing :durative-actions :numeric-fluents :universal-preconditions :equality)

  (:types 
    robot crate location group
  )

  (:predicates
    (at ?r - robot ?l - location)
    (crate-at ?c - crate ?l - location)
    (crate-loaded ?c - crate)
    (is-heavy ?c - crate)
    (is-fragile ?c - crate)
    (free ?r - robot)
    (loading-in-progress-primary)
    (loading-in-progress-secondary)
    (crate-group ?c - crate ?g - group)
    (group-next ?c1 - crate ?c2 - crate)
    (group-loaded ?g - group)
    (currently-in-loading-bay ?r - robot)
    (is-loading-bay ?l - location)
    (has-arrived-at ?r - robot ?to - location)
    (recharge-station ?l - location)
    (is-midpoint ?l - location)
    (is-relay-required ?c - crate)
  )

  (:functions
    (weight ?c - crate)
    (battery-level ?r - robot)
    (total-time)
    (distance-between ?from - location ?to - location)
  )
  ;; mark-ready-in-loading-bay (mark the robot ready in the loading-bay for the charging )
  (:durative-action mark-ready-in-loading-bay
    :parameters (?r - robot)
    :duration (= ?duration 0.0001)
    :condition (at start (at ?r loading-bay))
    :effect (at end (currently-in-loading-bay ?r))
  ) 
  
  ;;  move-empty-from-loading-bay(move crates from the loading-bay to any location)
  (:durative-action move-empty-from-loading-bay
    :parameters (?r - robot ?from ?to - location)
    :duration (= ?duration (/ (distance-between ?from ?to) 10))
    :condition (and
      (at start (at ?r ?from))
      (at start (free ?r))
      (at start (is-loading-bay ?from))
      (at start (>= (battery-level ?r) (/ (distance-between ?from ?to) 10)))
      (at start (exists (?c - crate) (crate-at ?c ?to)))
  )
    :effect (and
      (at start (not (at ?r ?from)))
      (at end (at ?r ?to))
      (at end (decrease (battery-level ?r) (/ (distance-between ?from ?to) 10)))
      (at end (not (currently-in-loading-bay ?r)))
      (at end (has-arrived-at ?r ?to))
      (at end (increase (total-time) ?duration))
  )
)
  ;; move-empty-to-loading-bay (move crates from location (specially here from midpoint) to the loading-bay)
  (:durative-action move-empty-to-loading-bay
    :parameters (?r - robot ?mid ?to - location)
    :duration (= ?duration (/ (distance-between ?mid ?to) 10))
    :condition (and
      (at start (at ?r ?mid))
      (at start (free ?r))
      (at start (is-midpoint ?mid)) ; restricts origin to midpoint
      (at start (is-loading-bay ?to))
      (at start (>= (battery-level ?r) (/ (distance-between ?mid ?to) 10)))
  )
    :effect (and
      (at start (not (at ?r ?mid)))
      (at end (at ?r ?to))
      (at end (decrease (battery-level ?r) (/ (distance-between ?mid ?to) 10)))
      (at end (not (currently-in-loading-bay ?r)))
      (at end (has-arrived-at ?r ?to))
      (at end (increase (total-time) ?duration))
  )
)
  ;; move-empty-general (move between locations)
  (:durative-action move-empty-general
    :parameters (?r - robot ?from ?to - location)
    :duration (= ?duration (/ (distance-between ?from ?to) 10))
    :condition (and
      (at start (at ?r ?from))
      (at start (free ?r))
      (at start (not (= ?from loading-bay)))
      (at start (not (= ?to loading-bay)))
      (at start (not (= ?from ?to)))
      (at start (>= (battery-level ?r) (/ (distance-between ?from ?to) 10)))
      (at start (exists (?c - crate) (crate-at ?c ?to)))
    )
    :effect (and
      (at start (not (at ?r ?from)))
      (at end (at ?r ?to))
      (at end (decrease (battery-level ?r) (/ (distance-between ?from ?to) 10)))
      (at end (not (currently-in-loading-bay ?r)))
      (at end (has-arrived-at ?r ?to))
      (at end (increase (total-time) ?duration))
    )
  )
   ;; move-crate-duo-relay (move crate from location to midpoint , also when we have the crate is unreachable . This action is used only for heavy crates , because of the unreachable crate3 in problem 3. )
  (:durative-action move-crate-duo-relay
    :parameters (?r1 ?r2 - robot ?c - crate ?from ?mid - location)
    :duration (= ?duration (/ (* (distance-between ?from ?mid) (weight ?c)) 100))
    :condition (and
      (at start (crate-at ?c ?from))
      (at start (not (crate-loaded ?c)))
      (at start (not (= ?from ?mid)))
      (at start (at ?r1 ?from))
      (at start (at ?r2 ?from))
      (at start (free ?r1))
      (at start (free ?r2))
      (at start (not (= ?r1 ?r2)))
      (at start (is-heavy ?c))
      (at start (is-midpoint ?mid))
      (at start (>= (battery-level ?r1) (/ (* (distance-between ?from ?mid) (weight ?c)) 100)))
      (at start (>= (battery-level ?r2) (/ (* (distance-between ?from ?mid) (weight ?c)) 100)))
      (over all (at ?r1 ?from))
      (over all (at ?r2 ?from))
      (over all (not (crate-loaded ?c)))
      (over all (forall (?c1 - crate)
        (imply (group-next ?c1 ?c)
               (crate-loaded ?c1))))
    )
    :effect (and
      (at start (not (free ?r1)))
      (at start (not (free ?r2)))
      (at start (not (crate-at ?c ?from)))
      (at end (free ?r1))
      (at end (free ?r2))
      (at end (crate-at ?c ?mid))
      (at end (at ?r1 ?mid))
      (at end (at ?r2 ?mid))
      (at end (not (at ?r1 ?from)))
      (at end (not (at ?r2 ?from)))
      (at end (decrease (battery-level ?r1) (/ (* (distance-between ?from ?mid) (weight ?c)) 100)))
      (at end (decrease (battery-level ?r2) (/ (* (distance-between ?from ?mid) (weight ?c)) 100)))
      (at end (increase (total-time) ?duration))
    )
  )
   ;; move-crate-duo-to-final (move crate from midpoint to loading-bay , used only when the crate is unreachable)
  (:durative-action move-crate-duo-to-final
    :parameters (?r1 ?r2 - robot ?c - crate ?mid ?to - location)
    :duration (= ?duration (/ (* (distance-between ?mid ?to) (weight ?c)) 100))
    :condition (and
      (at start (crate-at ?c ?mid))
      (at start (is-midpoint ?mid))
      (at start (at ?r1 ?mid))
      (at start (at ?r2 ?mid))
      (at start (free ?r1))
      (at start (free ?r2))
      (at start (not (= ?r1 ?r2)))
      (at start (is-heavy ?c))
      (at start (not (= ?mid ?to)))
      (at start (= ?to loading-bay))
      (at start (>= (battery-level ?r1) (/ (* (distance-between ?mid ?to) (weight ?c)) 100)))
      (at start (>= (battery-level ?r2) (/ (* (distance-between ?mid ?to) (weight ?c)) 100)))
      (over all (not (crate-loaded ?c)))
      (over all (at ?r1 ?mid))
      (over all (at ?r2 ?mid))
      (at start (imply (= ?to loading-bay)
                       (and (not (loading-in-progress-primary)) (not (loading-in-progress-secondary)))))
      (over all (not (loading-in-progress-secondary))) 
      (over all (not (loading-in-progress-primary)))
      (over all (forall (?c1 - crate)
        (imply (group-next ?c1 ?c)
               (crate-loaded ?c1))))
    )
    :effect (and
      (at start (not (free ?r1)))
      (at start (not (free ?r2)))
      (at end (free ?r1))
      (at end (free ?r2))
      (at end (crate-at ?c ?to))
      (at end (not (crate-at ?c ?mid)))
      (at end (not (at ?r1 ?mid)))
      (at end (not (at ?r2 ?mid)))
      (at end (at ?r1 ?to))
      (at end (at ?r2 ?to))
      (at end (decrease (battery-level ?r1) (/ (* (distance-between ?mid ?to) (weight ?c)) 100)))
      (at end (decrease (battery-level ?r2) (/ (* (distance-between ?mid ?to) (weight ?c)) 100)))
      (at end (increase (total-time) ?duration))
    )
  )
    ;; move-crate-single (move light crates with only one robot)
  (:durative-action move-crate-single
    :parameters (?r - robot ?c - crate ?from - location ?to - location)
    :duration (= ?duration (/ (* (distance-between ?from ?to) (weight ?c)) 100))
    :condition (and 
      (at start (crate-at ?c ?from))
      (at start (not (crate-loaded ?c)))
      (over all (not (crate-loaded ?c)))
      (at start (not (= ?from ?to)))
      (at start (at ?r ?from))
      (over all (at ?r ?from))
      (at start (not (is-heavy ?c)))
      (at start (not (is-fragile ?c)))
      (at start (free ?r))
      (at start (imply (= ?to loading-bay)
                       (and (not (loading-in-progress-primary)) (not (loading-in-progress-secondary)))))
      (over all (not (loading-in-progress-secondary))) 
      (over all (not (loading-in-progress-primary)))                
      (at start (>= (battery-level ?r) (/ (* (distance-between ?from ?to) (weight ?c)) 100)))
      (over all (forall (?c1 - crate)
        (imply (group-next ?c1 ?c)
               (crate-loaded ?c1))))
    )
    :effect (and 
      (at start (not (free ?r)))
      (at end (free ?r))
      (at end (crate-at ?c ?to))
      (at end (at ?r ?to))
      (at start (not (crate-at ?c ?from)))
      (at end (decrease (battery-level ?r) (/ (* (distance-between ?from ?to) (weight ?c)) 100)))
      (at end (not (at ?r ?from)))
      (at end (increase (total-time) ?duration))
    )
  )

    ;; move-crate-light-duo (move light crates with two robots to minimize time)
  (:durative-action move-crate-light-duo
    :parameters (?r1 ?r2 - robot ?c - crate ?from ?to - location)
    :duration (= ?duration (/ (* (distance-between ?from ?to) (weight ?c)) 150))
    :condition (and
      (at start (crate-at ?c ?from))
      (at start (not (crate-loaded ?c)))
      (over all (not (crate-loaded ?c)))
      (at start (not (= ?from ?to)))
      (at start (at ?r1 ?from))
      (at start (at ?r2 ?from))
      (over all (at ?r1 ?from))
      (over all (at ?r2 ?from))
      (at start (free ?r1))
      (at start (free ?r2))
      (at start (not (= ?r1 ?r2)))
      (at start (not (is-heavy ?c)))
      (at start (imply (= ?to loading-bay)
                       (and (not (loading-in-progress-primary)) (not (loading-in-progress-secondary)))))
      (over all (not (loading-in-progress-secondary))) 
      (over all (not (loading-in-progress-primary)))                 
      (at start (>= (battery-level ?r1) (/ (* (distance-between ?from ?to) (weight ?c)) 150)))
      (at start (>= (battery-level ?r2) (/ (* (distance-between ?from ?to) (weight ?c)) 150)))
      (over all (forall (?c1 - crate)
        (imply (group-next ?c1 ?c)
               (crate-loaded ?c1))))
    )
    :effect (and
      (at start (not (free ?r1)))
      (at start (not (free ?r2)))
      (at end (free ?r1))
      (at end (free ?r2))
      (at end (crate-at ?c ?to))
      (at end (at ?r1 ?to))
      (at end (at ?r2 ?to))
      (at start (not (crate-at ?c ?from)))
      (at end (not (at ?r1 ?from)))
      (at end (not (at ?r2 ?from)))
      (at end (decrease (battery-level ?r1) (/ (* (distance-between ?from ?to) (weight ?c)) 150)))
      (at end (decrease (battery-level ?r2) (/ (* (distance-between ?from ?to) (weight ?c)) 150)))
      (at end (increase (total-time) ?duration))
    )
  )

  ;; move-crate-duo (for heavy crates)
  (:durative-action move-crate-duo
    :parameters (?r1 ?r2 - robot ?c - crate ?from ?to - location)
    :duration (= ?duration (/ (* (distance-between ?from ?to) (weight ?c)) 100))
    :condition (and
      (at start (crate-at ?c ?from))
      (at start (not (crate-loaded ?c)))
      (over all (not (crate-loaded ?c)))
      (at start (not (= ?from ?to)))
      (at start (at ?r1 ?from))
      (at start (at ?r2 ?from))
      (over all (at ?r1 ?from))
      (over all (at ?r2 ?from))
      (at start (not (is-relay-required ?c)))
      (at start (is-heavy ?c))
      (at start (not (= ?r1 ?r2)))
      (at start (free ?r1))
      (at start (free ?r2))
      (at start (imply (= ?to loading-bay)
                       (and (not (loading-in-progress-primary)) (not (loading-in-progress-secondary)))))
      (over all (not (loading-in-progress-secondary))) 
      (over all (not (loading-in-progress-primary)))
      (at start (>= (battery-level ?r1) (/ (* (distance-between ?from ?to) (weight ?c)) 100)))
      (at start (>= (battery-level ?r2) (/ (* (distance-between ?from ?to) (weight ?c)) 100)))
      (over all (forall (?c1 - crate)
        (imply (group-next ?c1 ?c)
               (crate-loaded ?c1))))
    )
    :effect (and
      (at start (not (free ?r1)))
      (at start (not (free ?r2)))
      (at end (free ?r1))
      (at end (free ?r2))
      (at end (crate-at ?c ?to))
      (at end (at ?r1 ?to))
      (at end (at ?r2 ?to))
      (at start (not (crate-at ?c ?from)))
      (at end (not (at ?r1 ?from)))
      (at end (not (at ?r2 ?from)))
      (at end (decrease (battery-level ?r1) (/ (* (distance-between ?from ?to) (weight ?c)) 100)))
      (at end (decrease (battery-level ?r2) (/ (* (distance-between ?from ?to) (weight ?c)) 100)))
      (at end (increase (total-time) ?duration))
    )
  )
  
   ;; Primary loader (everything except fragile heavy)
  (:durative-action load-crate-primary
    :parameters (?c - crate)
    :duration (= ?duration 4)
    :condition (and
      (at start (crate-at ?c loading-bay))
      (at start (not (loading-in-progress-primary)))
      (at start (not (is-fragile ?c)))
      (at start (is-heavy ?c))
      (over all (forall (?c1 - crate)
        (imply (group-next ?c1 ?c)
             (crate-loaded ?c1))))
  )
    :effect (and
      (at start (loading-in-progress-primary))
      (at end (crate-loaded ?c))
      (at end (not (crate-at ?c loading-bay)))
      (at end (not (loading-in-progress-primary)))
      (at end (increase (total-time) ?duration))
  )
)

   ;; Fragile crate loader Primary loader ( can load Fragile crates that are heavy)
  (:durative-action load-crate-fragile-primary
    :parameters (?c - crate)
    :duration (= ?duration 6)
    :condition (and
      (at start (crate-at ?c loading-bay))
      (at start (is-fragile ?c))
      (at start (is-heavy ?c))
      (at start (not (loading-in-progress-primary)))
      (over all (forall (?c1 - crate)
        (imply (group-next ?c1 ?c)
             (crate-loaded ?c1))))
  )
    :effect (and
      (at start (loading-in-progress-primary))
      (at end (crate-loaded ?c))
      (at end (not (crate-at ?c loading-bay)))
      (at end (not (loading-in-progress-primary)))
      (at end (increase (total-time) ?duration))
  )
)

   ;; Secondary loader (can only load light crates that are  non-heavy and non-fragile)
  (:durative-action load-crate-secondary
    :parameters (?c - crate)
    :duration (= ?duration 4)
    :condition (and 
      (at start (crate-at ?c loading-bay))
      (at start (not (is-fragile ?c)))
      (at start (not (is-heavy ?c)))
      (at start (not (loading-in-progress-secondary)))
      (over all (forall (?c1 - crate)
        (imply (group-next ?c1 ?c)
             (crate-loaded ?c1))))
  )
    :effect (and 
      (at start (loading-in-progress-secondary))
      (at end (crate-loaded ?c))
      (at end (not (crate-at ?c loading-bay)))
      (at end (not (loading-in-progress-secondary)))
      (at end (increase (total-time) ?duration))
  )
)

;; Fragile crate Secondary loader (can only load fragile crates that are non-heavy)
  (:durative-action load-crate-fragile-secondary
    :parameters (?c - crate)
    :duration (= ?duration 6)
    :condition (and
      (at start (crate-at ?c loading-bay))
      (at start (is-fragile ?c))
      (at start (not (is-heavy ?c))) 
      (at start (not (loading-in-progress-secondary)))
      (over all (forall (?c1 - crate)
        (imply (group-next ?c1 ?c)
             (crate-loaded ?c1))))
  )
    :effect (and
      (at start (loading-in-progress-secondary))
      (at end (crate-loaded ?c))
      (at end (not (crate-at ?c loading-bay)))
      (at end (not (loading-in-progress-secondary)))
      (at end (increase (total-time) ?duration))
  )
)

  ;; recharge action (recharge is in the loading-bay)
  (:durative-action recharge
    :parameters (?r - robot)
    :duration (= ?duration 5)
    :condition (and
      (at start (at ?r loading-bay))
      (over all (at ?r loading-bay))
      (at start (currently-in-loading-bay ?r))
      (over all (currently-in-loading-bay ?r))
    )
    :effect (and
      (at end (assign (battery-level ?r) 20))
    )
  )
)